### ISSUE TITLE
Doesn't seem to support German special characters (Umlaute) like ä, ü, ö, ß

### ISSUE THREAD

**Issue by RaffCode-Personal** [savbell/whisper-writer#26] opened 2024-01-19 09:28 UTC
I attached a voice recording that should transcribe to "Es wäre schön, wenn das Programm auch Umlaute unterstützen würde." 

https://www.dropbox.com/scl/fi/5jez2tuqyjzxxpemtmz12/Umlaute.mp3?rlkey=mure8ckqmc801dgmfsox6f9bq&dl=0

Instead the output is this: "Es wre schn, wenn das Programm auch Umlaute untersttzen wrde."

**Comment by thfrei** [comment] 2024-01-22 18:13
I forked it and did some rework. Umlaute work for me. Maybe it is because I changed something with keyboard input?
https://github.com/thfrei/whisper-writer

**Comment by thfrei** [comment] 2024-01-22 18:15
> Transcription: an jemandem Maß nehmen.

` an jemandem MaS nehmen. ` 

> Transcription: Kopf bis Fuß.

` Kopf bis FuS.` 

Ok, "scharf-S" funktioniert noch nicht.

**Comment by savbell** [comment] 2024-01-26 01:14
Hi, thanks for the bug report! :)

When I tried running the mp3 with the local model, I got "Es wäre schön, wenn das Programm auch Umlaute unterstützen würde." With the API, I got "Es wäre schön, wenn das Programm auch Umlaut zu unterstützen würde."

@RaffCode-Personal, are you running from the latest commit? Special character transcription was an issue with an older version and was fixed when we switched to using `pynput` instead of `pyautogui`: https://github.com/savbell/whisper-writer/issues/9

**Comment by CsehAbel** [comment] 2024-03-10 16:32
I can confirm that it works.  It works perfectly with accented characters, starting from the commit that replaced pyinput with pyautogui for typing the characters.

**Comment by savbell** [comment] 2024-05-12 21:03
Closing the issue as it seems to be resolved. Thanks everyone!

**Closed by savbell** 2024-05-12 21:03 UTC
